# Generated by Django 4.2.3 on 2023-08-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='area',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='is_independent',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
